---
- name: Production Ready Automated NFS Server Configuration
  hosts: nfs_clients
  gather_facts: true
  become: true

  vars_files:
    - vault.yml

  vars:
    ansible_user: hpuser
    ansible_become_password: "{{ vault_hpuser_password }}"

  roles:
    - nfs_server
